### ISSUE TITLE
ActiveRecord::ConfigurationError in v1.2.1

### ISSUE THREAD

**Issue by noordean** [mrkamel/search_cop#70]
We upgraded to the latest version and we started having the above error. We have gone back to v1.2.0 for now as that works for us.

The complete error message: `ActiveRecord::ConfigurationError: Can't join 'Notes::Note' to association named 'notes/notes'; perhaps you misspelled it?`

Note: The searchable model is `Note`, namespaced under the `Notes` module.

I hope to find some time this week to look deeper into this and see if I can figure out exactly what is happening.

**Comment by noordean** [comment]
Here's it:

```
    search_scope :search do
      attributes :created_at, :completed, :due_date, :flagged, :category, :body
    end

    search_scope :search_user do
      attributes :created_at, :completed, :due_date, :flagged, :category, :body
      attributes user: 'user.name'
    end

    search_scope :search_assignee do
      attributes :created_at, :completed, :due_date, :flagged, :category, :body
      attributes assignees: ['assignees.name']
    end

    search_scope :search_by_step do
      attributes :current_step_body
    end
```
   
 Thanks for you quick response by the way.

**Comment by mrkamel** [comment]
v1.2.2 released which should fix it. Re-open otherwise.

**Comment by noordean** [comment]
Sorry for my late response. It's not fixed yet. I get this error now:

```
rails_1         | uninitialized constant Note
rails_1         | Did you mean?  Notes
rails_1         | /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/inflector/methods.rb:274:in `const_get'
rails_1         | /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/inflector/methods.rb:274:in `constantize'
rails_1         | /usr/local/bundle/gems/activesupport-6.1.4.7/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar/attributes.rb:81:in `klass_for'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar/attributes.rb:92:in `attribute_for'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar/attributes.rb:62:in `block in attributes'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar/attributes.rb:62:in `collect'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar/attributes.rb:62:in `attributes'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar/attributes.rb:54:in `compatible?'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:90:in `block in evaluate'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:90:in `select'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:90:in `evaluate'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:112:in `evaluate'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:17:in `collect'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:17:in `evaluate'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:119:in `evaluate'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:17:in `collect'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop_grammar.rb:17:in `evaluate'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop/grammar_parser.rb:18:in `parse'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop.rb:28:in `parse'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop/query_builder.rb:9:in `initialize'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop.rb:64:in `new'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop.rb:64:in `unsafe_search_cop'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop.rb:56:in `search_cop'
rails_1         | /usr/local/bundle/bundler/gems/search_cop-55ff5aea76cc/lib/search_cop.rb:47:in `block in search_scope'
rails_1         | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/relation/delegation.rb:108:in `public_send'
rails_1         | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/relation/delegation.rb:108:in `block in method_missing'
rails_1         | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/relation.rb:406:in `block in scoping'
rails_1         | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/relation.rb:804:in `_scoping'
rails_1         | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/relation.rb:406:in `scoping'
rails_1         | /usr/local/bundle/gems/activerecord-6.1.4.7/lib/active_record/relation/delegation.rb:108:in `method_missing'
```

**Comment by mrkamel** [comment]
ok, thanks, i was able to reproduce it and pushed a fix. Could you please verify via

```ruby
gem "search_cop", git: "https://github.com/mrkamel/search_cop", branch: "fix-inherited-and-namespaced-models"
```

thanks.

**Comment by noordean** [comment]
Ok, give me a few minutes.

**Comment by mrkamel** [comment]
thanks for checking. v1.2.3 released
